name: Deploy

on: [push, pull_request]

jobs:
  deploy:
    name: Deploy GitHub Page
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Setup Node.js 16.14.0
        uses: actions/setup-node@master
        with:
          node-version: 16.14.0

      - name: Install Dependencies
        run: yarn --frozen-lockfile

      - run: yarn build
      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: build
          token: ${{ secrets.GITHUB_TOKEN }}