name: Deploy

on: [push, pull_request]

jobs:
  deploy:
    name: Deploy GitHub Page
    runs-on: ubuntu-latest
    env:
      CI: true
    timeout-minutes: 30
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Setup Node.js 16.14.0
        uses: actions/setup-node@master
        with:
          node-version: 16.14.0

      - name: Install Dependencies
        run: yarn --frozen-lockfile

      - name: Setup git config
        run: |
          git config user.name "Tom Chen"
          git config user.email "tomking.chen@gmail.com"

      - name: Deploy GitHub page
        run: yarn deploy
        env:
          GITHUB_TOKEN: ${{ github.token }}